### PR TITLE
add camera tap focus and new test cases

### PR DESCRIPTION
**Pull request by MikeLien**
1. camera tap focus on camera preview, camera picture, and camera video
2. new test cases: video and background music playback

### CODE REVIEW

**Comment by MikeLien** [comment]
1. the camera tap behavior will consume more power and avoid different focus area by auto focus
2. new test cases use contents under source folder as the benchmark and these files also used by manually test

**Comment by JonHylands** [comment]
Mike - I like your new tests, and specifically how you solved pushing the local data to the phone - I wasn't sure how to do that. However, I don't like the duplication of all the support code in your new test_media_playback.py file. If we're going to break up the test code into separate files, we need to pull out the support code, and put it in another file that all the test files can import.

**Comment by MikeLien** [comment]
During writing test cases, I refer to some related gaia-ui-test cases to solve my problem. I find the push method there.
And sure, I agree we should avoid the duplication part. Besides, we need to design different cases have its corresponding prerequisites settings. Because I don't know how you want to do that, I just duplicate another one and change the settings part.

**Comment by JonHylands** [comment]
I've merged your changes, and I'll extract the common stuff and refactor.

**Pull request merged**
